// Code generated by sham. DO NOT EDIT.
// https://github.com/jmalloc/sham

package outputs

import (
	"io"

	inputs "github.com/jmalloc/sham/generator/testdata/inputs"
)

// Imports is a test implementation of the inputs.Imports interface.
type Imports struct {
	// Imports is the default implementation of the interface.
	// If it is nil, each method will return an error (or panic).
	inputs.Imports

	// MethodFunc is an implementation of the Method() method.
	// If it is non-nil, it takes precedence over the embedded Imports interface.
	MethodFunc func(io.Writer)
}

func (stub *Imports) Method(w io.Writer) {
	if stub.MethodFunc != nil {
		stub.MethodFunc(w)
	}

	if stub.Imports != nil {
		stub.Imports.Method(w)
	}
}
