// Code generated by sham. DO NOT EDIT.

package outputs

import (
	"io"

	inputs "github.com/jmalloc/sham/generator/testdata/inputs"
)

// InputParam is a test implementation of the inputs.InputParam interface.
type InputParam struct {
	inputs.InputParam

	// MethodFunc is a stub for the Method() method.
	// If it is non-nil, it takes precedence over x.InputParam.Method().
	MethodFunc func(io.Writer)
}

func (x *InputParam) Method(w io.Writer) {
	if x.MethodFunc != nil {
		x.MethodFunc(w)
	}

	if x.InputParam != nil {
		x.InputParam.Method(w)
	}
}
