// Code generated by sham. DO NOT EDIT.

package fixtures

// Inputs is a test implementation of the somepackage.Inputs interface.
type Inputs struct {
	MFunc func(*pkg.Type)
}

func (x *Inputs) M(in *pkg.Type) {
	if x.MFunc != nil {
		x.MFunc(in)
	}
}
