// Code generated by sham. DO NOT EDIT.

package outputs

import inputs "github.com/jmalloc/sham/generator/testdata/inputs"

// OutputParam is a test implementation of the inputs.OutputParam interface.
type OutputParam struct {
	// OutputParam is the default implementation of the interface.
	// If it is nil, each method will return an error (or panic).
	inputs.OutputParam

	// AnonFunc is an implementation of the Anon() method.
	// If it is non-nil, it takes precedence over the embedded inputs.OutputParam implementation.
	AnonFunc func() int

	// SingleFunc is an implementation of the Single() method.
	// If it is non-nil, it takes precedence over the embedded inputs.OutputParam implementation.
	SingleFunc func() int
}

func (x *OutputParam) Anon() int {
	if x.AnonFunc != nil {
		return x.AnonFunc()
	}

	if x.OutputParam != nil {
		return x.OutputParam.Anon()
	}

	panic("Anon() has no implementation, set the OutputParam or AnonFunc field")
}

func (x *OutputParam) Single() (a int) {
	if x.SingleFunc != nil {
		return x.SingleFunc()
	}

	if x.OutputParam != nil {
		return x.OutputParam.Single()
	}

	panic("Single() has no implementation, set the OutputParam or SingleFunc field")
}
