// Code generated by sham. DO NOT EDIT.

package outputs

import inputs "github.com/jmalloc/sham/generator/testdata/inputs"

// Empty is a test implementation of the inputs.Empty interface.
type Empty struct{}

// Assert that Empty implements inputs.Empty.
var _ inputs.Empty = (*Empty)(nil)
