// Code generated by sham. DO NOT EDIT.

package outputs

import inputs "github.com/jmalloc/sham/generator/testdata/inputs"

// InputParam is a test implementation of the inputs.InputParam interface.
type InputParam struct {
	// InputParam is the default implementation of the interface.
	// If it is nil, each method will return an error (or panic).
	inputs.InputParam

	// AnonFunc is an implementation of the Anon() method.
	// If it is non-nil, it takes precedence over the embedded InputParam interface.
	AnonFunc func(int)

	// SingleFunc is an implementation of the Single() method.
	// If it is non-nil, it takes precedence over the embedded InputParam interface.
	SingleFunc func(int)

	// MultipleFunc is an implementation of the Multiple() method.
	// If it is non-nil, it takes precedence over the embedded InputParam interface.
	MultipleFunc func(int, float64)

	// MultipleNamesFunc is an implementation of the MultipleNames() method.
	// If it is non-nil, it takes precedence over the embedded InputParam interface.
	MultipleNamesFunc func(int, int)

	// VariadicFunc is an implementation of the Variadic() method.
	// If it is non-nil, it takes precedence over the embedded InputParam interface.
	VariadicFunc func(...int)

	// ReceiverCollisionFunc is an implementation of the ReceiverCollision() method.
	// If it is non-nil, it takes precedence over the embedded InputParam interface.
	ReceiverCollisionFunc func(int)
}

func (x *InputParam) Anon(_0 int) {
	if x.AnonFunc != nil {
		x.AnonFunc(_0)
	}

	if x.InputParam != nil {
		x.InputParam.Anon(_0)
	}
}

func (x *InputParam) Single(v int) {
	if x.SingleFunc != nil {
		x.SingleFunc(v)
	}

	if x.InputParam != nil {
		x.InputParam.Single(v)
	}
}

func (x *InputParam) Multiple(a int, b float64) {
	if x.MultipleFunc != nil {
		x.MultipleFunc(a, b)
	}

	if x.InputParam != nil {
		x.InputParam.Multiple(a, b)
	}
}

func (x *InputParam) MultipleNames(a, b int) {
	if x.MultipleNamesFunc != nil {
		x.MultipleNamesFunc(a, b)
	}

	if x.InputParam != nil {
		x.InputParam.MultipleNames(a, b)
	}
}

func (x *InputParam) Variadic(args ...int) {
	if x.VariadicFunc != nil {
		x.VariadicFunc(args...)
	}

	if x.InputParam != nil {
		x.InputParam.Variadic(args...)
	}
}

func (x0 *InputParam) ReceiverCollision(x int) {
	if x0.ReceiverCollisionFunc != nil {
		x0.ReceiverCollisionFunc(x)
	}

	if x0.InputParam != nil {
		x0.InputParam.ReceiverCollision(x)
	}
}
