// Code generated by sham. DO NOT EDIT.

package outputs

import inputs "github.com/jmalloc/sham/generator/testdata/inputs"

// InputParam is a test implementation of the inputs.InputParam interface.
type InputParam struct {
	inputs.InputParam

	// ScalarFunc is an implementation of the Scalar() method.
	// If it is non-nil, it takes precedence over x.InputParam.Scalar().
	ScalarFunc func(int)
}

func (x *InputParam) Scalar(v int) {
	if x.ScalarFunc != nil {
		x.ScalarFunc(v)
	}

	if x.InputParam != nil {
		x.InputParam.Scalar(v)
	}
}
