// Code generated by sham. DO NOT EDIT.

package outputs

// Nullary is a test implementation of the somepackage.Nullary interface.
type Nullary struct {
	MFunc func()
}

func (x *Nullary) M() {
	if x.MFunc != nil {
		x.MFunc()
	}
}
