// Code generated by sham. DO NOT EDIT.

package outputs

import inputs "github.com/jmalloc/sham/generator/testdata/inputs"

// Nullary is a test implementation of the inputs.Nullary interface.
type Nullary struct {
	inputs.Nullary

	// MethodFunc is an implementation of the Method() method.
	// If it is non-nil, it takes precedence over x.Nullary.Method().
	MethodFunc func()
}

func (x *Nullary) Method() {
	if x.MethodFunc != nil {
		x.MethodFunc()
	}

	if x.Nullary != nil {
		x.Nullary.Method()
	}
}
